Criação de roteadores
Maua-Dev/back_fastAPI_template pull request #33
Opened 2021-09-30 18:08 UTC by Renan-Reschke

2021-10-01 02:47 UTC, VitorMartin requested changes

2021-10-01 02:47 UTC, VitorMartin commented on src/main.py
> +    _ctrl.app.include_router(roteador)
Joga isso pra dentro da fabrica do FastAPI:

`src/fabricas/controladores/fastapi/fabrica_controlador_fastapi.py` depois da linha 34 (`self.app = FastAPI()`)

2021-10-01 23:50 UTC, Brvilardi commented on src/controladores/fastapi/roteadores/roteadores.py
> +(_, _ctrl) = Init()()
@VitorMartin , se o Init na main mudar, aqui vai mudar também?

Tipo se rodarmos "py -m src.py --repo=mysql", o Init( )( ) do uvicorn.run( ) vai ter o repo de mysql, mas e os repos do roteador, vao ter o mysql como repo tb??

2021-10-02 03:16 UTC, VitorMartin commented on src/controladores/fastapi/roteadores/roteadores.py
> +(_, _ctrl) = Init()()
O `Init()` deve ser o ponto unico de entrada da nossa aplicacao, entao eu escrevi la no disc uma proposta pra arquitetar essa questao. Vamos tirar esse `Init()` dai do roteador.

Mas respondendo sua pergunta, esse Init conseguiria pegar dados do `config.json`, mas nao se a gnt passar os argumentos via codigo. Entao teria que mudar aqui tb, caso a gnt fosse passar os argumentos opcionais do `Init(tipo_repo, tipo_ctrl)`

2021-10-02 03:23 UTC, VitorMartin commented on src/controladores/fastapi/roteadores/roteadores.py
> +(_, _ctrl) = Init()()
https://github.com/Maua-Dev/back_fastAPI_template/pull/33#discussion_r720617643

2021-10-02 03:24 UTC, VitorMartin commented
Eu passei os detalhes de como arquitetar o roteador pelo Discord. Qqr coisa chama, blz?

2021-10-02 03:24 UTC, VitorMartin requested changes
Eu passei os detalhes de como arquitetar o roteador pelo Discord. Qqr coisa chama, blz?

2021-10-14 23:56 UTC, VitorMartin approved these changes, later dismissed

2021-10-15 01:06 UTC, VitorMartin approved these changes

2021-10-15 01:06 UTC, merged